security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur:
            algorithm: auto
        App\Entity\Administrateur:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # Provider pour les utilisateurs/clients
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
        # Provider pour les administrateurs
        app_admin_provider:
            entity:
                class: App\Entity\Administrateur
                property: email
        # Provider combiné (chaîne de providers)
        chain_provider:
            chain:
                providers: ['app_user_provider', 'app_admin_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: chain_provider

            # Configuration de l'authentificateur personnalisé
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

            # Configuration de la déconnexion
            logout:
                path: app_logout
                target: app_home

            # Remember me
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
                always_remember_me: false

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/client, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
